# Generated by Django 4.2.4 on 2024-08-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='share',
            field=models.CharField(default='', max_length=100, verbose_name='招待リンク・グループID'),
            preserve_default=False,
        ),
    ]
