# Generated by Django 4.2.4 on 2024-08-08 01:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_group_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
    ]
